server:
  port: 8100 #设置自定义的启动端口


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7500/eureka/
  instance:
    instance-id: woxingshop-database-8100 #配置中心中显示微服务的名称
    prefer-ip-address: true   #是否显示访问微服务的url（可选）

info:
  app.name: woxingshop-database-8100
  auther: 小丁
  message: 这是数据库的模块

spring:
  application:
    name: woxingshop-database-8100 #当前项目名，微服务的名字   非常重要
  mvc:
    static-path-pattern: /**
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/woniushop?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
      username: root #用户名
      password:  #密码
      initial-size: 1 #初始化大小
      min-idle: 5 #连接池最小连接数
      max-wait: 60000 #最大等待时间
      max-active: 20 #最大连接数量
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL #测试语句
  #redis:
    #database: 0  #数据库编号0
    #host: 127.0.0.1 #redis的ip
    #port: 6379   #端口
    #timeout: 300  #连接超时时间

mybatis:
  config-location: classpath:mybatis/mybatis-config-xml.xml
 # mapper-locations: classpath:mybatis/mapper/*.xml